// Code generated by mockery v2.42.1. DO NOT EDIT.

package initializer

import (
	mock "github.com/stretchr/testify/mock"
	kubernetes "k8s.io/client-go/kubernetes"
)

// MockInitializer is an autogenerated mock type for the Initializer type
type MockInitializer struct {
	mock.Mock
}

type MockInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInitializer) EXPECT() *MockInitializer_Expecter {
	return &MockInitializer_Expecter{mock: &_m.Mock}
}

// CreateClientSet provides a mock function with given fields:
func (_m *MockInitializer) CreateClientSet() (kubernetes.Interface, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateClientSet")
	}

	var r0 kubernetes.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func() (kubernetes.Interface, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() kubernetes.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kubernetes.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInitializer_CreateClientSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClientSet'
type MockInitializer_CreateClientSet_Call struct {
	*mock.Call
}

// CreateClientSet is a helper method to define mock.On call
func (_e *MockInitializer_Expecter) CreateClientSet() *MockInitializer_CreateClientSet_Call {
	return &MockInitializer_CreateClientSet_Call{Call: _e.mock.On("CreateClientSet")}
}

func (_c *MockInitializer_CreateClientSet_Call) Run(run func()) *MockInitializer_CreateClientSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInitializer_CreateClientSet_Call) Return(_a0 kubernetes.Interface, _a1 error) *MockInitializer_CreateClientSet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInitializer_CreateClientSet_Call) RunAndReturn(run func() (kubernetes.Interface, error)) *MockInitializer_CreateClientSet_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespace provides a mock function with given fields:
func (_m *MockInitializer) GetNamespace() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNamespace")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockInitializer_GetNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespace'
type MockInitializer_GetNamespace_Call struct {
	*mock.Call
}

// GetNamespace is a helper method to define mock.On call
func (_e *MockInitializer_Expecter) GetNamespace() *MockInitializer_GetNamespace_Call {
	return &MockInitializer_GetNamespace_Call{Call: _e.mock.On("GetNamespace")}
}

func (_c *MockInitializer_GetNamespace_Call) Run(run func()) *MockInitializer_GetNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInitializer_GetNamespace_Call) Return(_a0 string) *MockInitializer_GetNamespace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInitializer_GetNamespace_Call) RunAndReturn(run func() string) *MockInitializer_GetNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInitializer creates a new instance of MockInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInitializer {
	mock := &MockInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
