// Code generated by mockery v2.20.0. DO NOT EDIT.

package alias

import mock "github.com/stretchr/testify/mock"

// mockRegistryContext is an autogenerated mock type for the registryContext type
type mockRegistryContext struct {
	mock.Mock
}

type mockRegistryContext_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRegistryContext) EXPECT() *mockRegistryContext_Expecter {
	return &mockRegistryContext_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: key
func (_m *mockRegistryContext) Delete(key string) error {
	ret := _m.Called(key)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRegistryContext_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockRegistryContext_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *mockRegistryContext_Expecter) Delete(key interface{}) *mockRegistryContext_Delete_Call {
	return &mockRegistryContext_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *mockRegistryContext_Delete_Call) Run(run func(key string)) *mockRegistryContext_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockRegistryContext_Delete_Call) Return(_a0 error) *mockRegistryContext_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRegistryContext_Delete_Call) RunAndReturn(run func(string) error) *mockRegistryContext_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRecursive provides a mock function with given fields: key
func (_m *mockRegistryContext) DeleteRecursive(key string) error {
	ret := _m.Called(key)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRegistryContext_DeleteRecursive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRecursive'
type mockRegistryContext_DeleteRecursive_Call struct {
	*mock.Call
}

// DeleteRecursive is a helper method to define mock.On call
//   - key string
func (_e *mockRegistryContext_Expecter) DeleteRecursive(key interface{}) *mockRegistryContext_DeleteRecursive_Call {
	return &mockRegistryContext_DeleteRecursive_Call{Call: _e.mock.On("DeleteRecursive", key)}
}

func (_c *mockRegistryContext_DeleteRecursive_Call) Run(run func(key string)) *mockRegistryContext_DeleteRecursive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockRegistryContext_DeleteRecursive_Call) Return(_a0 error) *mockRegistryContext_DeleteRecursive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRegistryContext_DeleteRecursive_Call) RunAndReturn(run func(string) error) *mockRegistryContext_DeleteRecursive_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: key
func (_m *mockRegistryContext) Exists(key string) (bool, error) {
	ret := _m.Called(key)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRegistryContext_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type mockRegistryContext_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - key string
func (_e *mockRegistryContext_Expecter) Exists(key interface{}) *mockRegistryContext_Exists_Call {
	return &mockRegistryContext_Exists_Call{Call: _e.mock.On("Exists", key)}
}

func (_c *mockRegistryContext_Exists_Call) Run(run func(key string)) *mockRegistryContext_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockRegistryContext_Exists_Call) Return(_a0 bool, _a1 error) *mockRegistryContext_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRegistryContext_Exists_Call) RunAndReturn(run func(string) (bool, error)) *mockRegistryContext_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *mockRegistryContext) Get(key string) (string, error) {
	ret := _m.Called(key)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRegistryContext_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockRegistryContext_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *mockRegistryContext_Expecter) Get(key interface{}) *mockRegistryContext_Get_Call {
	return &mockRegistryContext_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *mockRegistryContext_Get_Call) Run(run func(key string)) *mockRegistryContext_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockRegistryContext_Get_Call) Return(_a0 string, _a1 error) *mockRegistryContext_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRegistryContext_Get_Call) RunAndReturn(run func(string) (string, error)) *mockRegistryContext_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *mockRegistryContext) GetAll() (map[string]string, error) {
	ret := _m.Called()

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRegistryContext_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type mockRegistryContext_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *mockRegistryContext_Expecter) GetAll() *mockRegistryContext_GetAll_Call {
	return &mockRegistryContext_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *mockRegistryContext_GetAll_Call) Run(run func()) *mockRegistryContext_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockRegistryContext_GetAll_Call) Return(_a0 map[string]string, _a1 error) *mockRegistryContext_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRegistryContext_GetAll_Call) RunAndReturn(run func() (map[string]string, error)) *mockRegistryContext_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrFalse provides a mock function with given fields: key
func (_m *mockRegistryContext) GetOrFalse(key string) (bool, string, error) {
	ret := _m.Called(key)

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (bool, string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// mockRegistryContext_GetOrFalse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrFalse'
type mockRegistryContext_GetOrFalse_Call struct {
	*mock.Call
}

// GetOrFalse is a helper method to define mock.On call
//   - key string
func (_e *mockRegistryContext_Expecter) GetOrFalse(key interface{}) *mockRegistryContext_GetOrFalse_Call {
	return &mockRegistryContext_GetOrFalse_Call{Call: _e.mock.On("GetOrFalse", key)}
}

func (_c *mockRegistryContext_GetOrFalse_Call) Run(run func(key string)) *mockRegistryContext_GetOrFalse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockRegistryContext_GetOrFalse_Call) Return(_a0 bool, _a1 string, _a2 error) *mockRegistryContext_GetOrFalse_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *mockRegistryContext_GetOrFalse_Call) RunAndReturn(run func(string) (bool, string, error)) *mockRegistryContext_GetOrFalse_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: key, timeToLiveInSeconds
func (_m *mockRegistryContext) Refresh(key string, timeToLiveInSeconds int) error {
	ret := _m.Called(key, timeToLiveInSeconds)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(key, timeToLiveInSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRegistryContext_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type mockRegistryContext_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - key string
//   - timeToLiveInSeconds int
func (_e *mockRegistryContext_Expecter) Refresh(key interface{}, timeToLiveInSeconds interface{}) *mockRegistryContext_Refresh_Call {
	return &mockRegistryContext_Refresh_Call{Call: _e.mock.On("Refresh", key, timeToLiveInSeconds)}
}

func (_c *mockRegistryContext_Refresh_Call) Run(run func(key string, timeToLiveInSeconds int)) *mockRegistryContext_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *mockRegistryContext_Refresh_Call) Return(_a0 error) *mockRegistryContext_Refresh_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRegistryContext_Refresh_Call) RunAndReturn(run func(string, int) error) *mockRegistryContext_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function with given fields:
func (_m *mockRegistryContext) RemoveAll() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRegistryContext_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type mockRegistryContext_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
func (_e *mockRegistryContext_Expecter) RemoveAll() *mockRegistryContext_RemoveAll_Call {
	return &mockRegistryContext_RemoveAll_Call{Call: _e.mock.On("RemoveAll")}
}

func (_c *mockRegistryContext_RemoveAll_Call) Run(run func()) *mockRegistryContext_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockRegistryContext_RemoveAll_Call) Return(_a0 error) *mockRegistryContext_RemoveAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRegistryContext_RemoveAll_Call) RunAndReturn(run func() error) *mockRegistryContext_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *mockRegistryContext) Set(key string, value string) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRegistryContext_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type mockRegistryContext_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *mockRegistryContext_Expecter) Set(key interface{}, value interface{}) *mockRegistryContext_Set_Call {
	return &mockRegistryContext_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *mockRegistryContext_Set_Call) Run(run func(key string, value string)) *mockRegistryContext_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *mockRegistryContext_Set_Call) Return(_a0 error) *mockRegistryContext_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRegistryContext_Set_Call) RunAndReturn(run func(string, string) error) *mockRegistryContext_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetWithLifetime provides a mock function with given fields: key, value, timeToLiveInSeconds
func (_m *mockRegistryContext) SetWithLifetime(key string, value string, timeToLiveInSeconds int) error {
	ret := _m.Called(key, value, timeToLiveInSeconds)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int) error); ok {
		r0 = rf(key, value, timeToLiveInSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRegistryContext_SetWithLifetime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWithLifetime'
type mockRegistryContext_SetWithLifetime_Call struct {
	*mock.Call
}

// SetWithLifetime is a helper method to define mock.On call
//   - key string
//   - value string
//   - timeToLiveInSeconds int
func (_e *mockRegistryContext_Expecter) SetWithLifetime(key interface{}, value interface{}, timeToLiveInSeconds interface{}) *mockRegistryContext_SetWithLifetime_Call {
	return &mockRegistryContext_SetWithLifetime_Call{Call: _e.mock.On("SetWithLifetime", key, value, timeToLiveInSeconds)}
}

func (_c *mockRegistryContext_SetWithLifetime_Call) Run(run func(key string, value string, timeToLiveInSeconds int)) *mockRegistryContext_SetWithLifetime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *mockRegistryContext_SetWithLifetime_Call) Return(_a0 error) *mockRegistryContext_SetWithLifetime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRegistryContext_SetWithLifetime_Call) RunAndReturn(run func(string, string, int) error) *mockRegistryContext_SetWithLifetime_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockRegistryContext interface {
	mock.TestingT
	Cleanup(func())
}

// newMockRegistryContext creates a new instance of mockRegistryContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockRegistryContext(t mockConstructorTestingTnewMockRegistryContext) *mockRegistryContext {
	mock := &mockRegistryContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
