apiVersion: v1
values:
  images:
    job: cloudogu/k8s-host-change:0.6.0
patches:
  values.yaml:
    job:
      image:
        registry: "{{ registryFrom .images.job }}"
        repository: "{{ repositoryFrom .images.job }}"
        tag: "{{ tagFrom .images.job }}"
