apiVersion: v1
values:
  images:
    job: cloudogu/k8s-host-change:0.3.1
patches:
  values.yaml:
    job:
      image:
        repository: "{{ registryFrom .images.job }}/{{ repositoryFrom .images.job }}"
        tag: "{{ tagFrom .images.job }}"
