apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8s-host-change.name" . }}
  labels:
    {{- include "k8s-host-change.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - env:
            - name: STAGE
              value: {{ .Values.job.env.stage | default "production" }}
            - name: LOG_LEVEL
              value: {{ .Values.job.env.logLevel | default "info" }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}
          name: k8s-host-change
          imagePullPolicy: {{ .Values.job.imagePullPolicy | default "IfNotPresent" }}
      restartPolicy: Never
      serviceAccountName: {{ include "k8s-host-change.name" . }}
