apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-host-change.name" . }}
  labels:
    {{- include "k8s-host-change.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - get
  - update
- apiGroups:
    - ""
  resources:
    - configmaps
  resourceNames:
    - "global-config"
  verbs:
    - list
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-host-change.name" . }}
  labels:
    {{- include "k8s-host-change.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "k8s-host-change.name" . }}'
subjects:
- kind: ServiceAccount
  name: '{{ include "k8s-host-change.name" . }}'
  namespace: '{{ .Release.Namespace }}'